# Generated by Django 5.1.15 on 2026-06-14 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("detection", "0001_initial"),
        ("modeling", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="detectionjob",
            name="model3d",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="detection_job",
                to="modeling.model3d",
            ),
        ),
    ]
