# Generated by Django 5.1.15 on 2026-06-14 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('glb_file', models.FileField(upload_to='models3d/')),
                ('scene_json', models.JSONField(blank=True, null=True)),
                ('bounds', models.JSONField(blank=True, null=True)),
                ('element_count', models.PositiveIntegerField(default=0)),
                ('model_name', models.CharField(blank=True, max_length=60)),
                ('unit', models.CharField(default='meters', max_length=20)),
                ('is_current', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models3d', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
