# Generated by Django 5.1.15 on 2026-06-14 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modeling', '0001_initial'),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model3d',
            name='source_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='models3d', to='plans.plan'),
        ),
        migrations.AddIndex(
            model_name='model3d',
            index=models.Index(fields=['project', 'is_current'], name='modeling_mo_project_e171cf_idx'),
        ),
    ]
