# Generated by Django 5.1.15 on 2026-06-22 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sketch_2d', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boceto2d',
            name='imagen_url',
        ),
    ]
